# Crypto 1

In [7]:
import numpy as np

### Task 1
Calculated 232 + 22 * 77 - 18^2 (mod 8)

In [8]:
print("Result:")
print((232 + 22 * 77 - 18 ** 2) % 8)

Result:
2


### Task 2
**a)** Skriv ut multiplikasjonstbellen Z_12, uten å ta med 0 (mod 12).

In [9]:
z12 = np.zeros((11, 11))

for x in range(11):
    for y in range(11):
        z12[x][y] = ((x+1) * (y+1))

z12 = np.mod(z12, 12)

print(z12)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 2.  4.  6.  8. 10.  0.  2.  4.  6.  8. 10.]
 [ 3.  6.  9.  0.  3.  6.  9.  0.  3.  6.  9.]
 [ 4.  8.  0.  4.  8.  0.  4.  8.  0.  4.  8.]
 [ 5. 10.  3.  8.  1.  6. 11.  4.  9.  2.  7.]
 [ 6.  0.  6.  0.  6.  0.  6.  0.  6.  0.  6.]
 [ 7.  2.  9.  4. 11.  6.  1.  8.  3. 10.  5.]
 [ 8.  4.  0.  8.  4.  0.  8.  4.  0.  8.  4.]
 [ 9.  6.  3.  0.  9.  6.  3.  0.  9.  6.  3.]
 [10.  8.  6.  4.  2.  0. 10.  8.  6.  4.  2.]
 [11. 10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]]


**b)** Hvilke tall har multiplikative invers modulo 12?

In [10]:
for x in range(11):
        for y in range(11):
            if z12[x][y] == 1:
                print(f'{x+1} has a multiplicative inverse with mod 12')

1 has a multiplicative inverse with mod 12
5 has a multiplicative inverse with mod 12
7 has a multiplicative inverse with mod 12
11 has a multiplicative inverse with mod 12


**c)** Forklar hvorfor en ikke kan ha 0 og 1 i samme rad eller kolonne i tabellen.

**Svar:**
Man kan ikke ha bå 0 og 1 i samme rad eller kolonne fordi man kun få 1, i en rad eller kolonnen dersom tallet (som raden eller kolonnen representerer) er relativt primisk med modulotallet (i dette tilfellet 12). For å kunne få 0, i en rad eller kolonnen, kan tallet IKKE være relativt primisk med modulotallet. 0 og 1 er derfor gjensidig utelukkende.

### Task 3

In [11]:
# TODO

### Task 4

**a)** Hvor mange forskjellige nøkler kan et (enkelt) substitusjonsChiffer ha når vi opererer med et alfabet med 29 tegn?

**Svar:** Vi kan ha 29! nøkler.

In [13]:
print(np.math.factorial(29))

8841761993739701954543616000000


**b)** Hvilke enkle grep kan Alice og Bob bruke for å gjøre det vanskeligere for Eva å dekode meldingene?

**Svar:** 
* Alice og Bob kan bruke to forskjellige nøkler, slik at om Eva knekker en av de, så kan hun kun lese halvparten av meldingene.
* Alice og Bob kan kutte ut kutte ut mellomrom eller dele opp klarteksten i blokker av en satt lengde slik at det blir vanskeligere gjenkjenne ord bassert på lengde.
* Alice og Bob kan kutte ut gjentagende fraser (f. eks "Hilsen Bob")

**c)** Hvis vi lager et substitusjonchiffer for blokker med *n* tegn, hvor mange nøkler finnes da?

**Svar:** Vi får (29^n)! 

### Task 5

Dekrypter denne strengen: 

**YÆVFB VBVFR ÅVBV** 

Den er kryptert med et k-skift-chiffer.

In [31]:
alphabet_number = {
    'a' : 0,
    'b' : 1,
    'c' : 2,
    'd' : 3,
    'e' : 4,
    'f' : 5,
    'g' : 6,
    'h' : 7,
    'i' : 8,
    'j' : 9,
    'k' : 10,
    'l' : 11,
    'm' : 12,
    'n' : 13,
    'o' : 14,
    'p' : 15,
    'q' : 16,
    'r' : 17,
    's' : 18,
    't' : 19,
    'u' : 20,
    'v' : 21,
    'w' : 22,
    'x' : 23,
    'y' : 24,
    'z' : 25,
    'æ' : 26,
    'ø' : 27,
    'å' : 28
    
}

alphabet = [
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z',
    'æ',
    'ø',
    'å'
]

def reformat_index(i):
    if i < 0:
        return 29 + i
    
    return i

In [32]:
input = "yævfbvbvfråvbv"
int_list = []

for char in input:
    int_list.append(alphabet_number[char])
    

In [34]:
for x in range(29):
    print(f'{x}:')
    output = ""
    for i in int_list:
        output += alphabet[reformat_index(i-x)]
    print(output)

0:
yævfbvbvfråvbv
1:
xzueauaueqøuau
2:
wytdåtåtdpætåt
3:
vxscøsøscozsøs
4:
uwrbærærbnyrær
5:
tvqazqzqamxqzq
6:
supåypypålwpyp
7:
rtoøxoxoøkvoxo
8:
qsnæwnwnæjunwn
9:
prmzvmvmzitmvm
10:
oqlyululyhslul
11:
npkxtktkxgrktk
12:
mojwsjsjwfqjsj
13:
lnivririvepiri
14:
kmhuqhqhudohqh
15:
jlgtpgpgtcngpg
16:
ikfsofofsbmfof
17:
hjerneneralene
18:
gidqmdmdqåkdmd
19:
fhcplclcpøjclc
20:
egbokbkboæibkb
21:
dfanjajanzhaja
22:
ceåmiåiåmygåiå
23:
bdølhøhølxføhø
24:
acækgægækweægæ
25:
åbzjfzfzjvdzfz
26:
øayieyeyiucyey
27:
æåxhdxdxhtbxdx
28:
zøwgcwcwgsawcw


**Svar:**

Krypteringsnøkkel: *17*

Klartekst: 
*hjern enera lene* -> *Hjernen er alene*

### Task 6

Definer et blokk-chiffer med blokklengde *b*, og et alfabet med *N* tegn, som bruker samme prinsikk som skift-chifret.

* Skriv opp en formell definisjon.

* Hvor mange forskjellige nøkler har chifret?


**Svar:** Dette chifret har *(N^b)!* nøkler.


### Task 7

Vigénere-chiffer.

**a)** Krypter teksten "Nå er det snart helg" med nøkkelordet "torsk".